# Generated by Django 5.0.4 on 2024-06-26 18:43
import random

from django.db import migrations


def generate_barcodes(apps, schema_editor):
    product_model = apps.get_model('main_app', 'Product')
    all_products = product_model.objects.all()
    barcodes = random.sample(range(100_000_000, 1_000_000_000), len(all_products))

    for product, barcode in zip(all_products, barcodes):
        product.barcode = barcode
        product.save()


def reverse_barcodes(apps, schema_editor):
    product_model = apps.get_model('main_app', 'Product')

    for product in product_model.objects.all():
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_barcode'),
    ]

    operations = [
        migrations.RunPython(generate_barcodes, reverse_barcodes)
    ]
