# Generated by Django 5.0.4 on 2024-07-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_subject_lecturer_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='main_app.subject'),
        ),
    ]
