# Generated by Django 5.0.4 on 2024-06-28 19:25

from django.db import migrations


def set_unique_brands(apps, schema_editor) -> None:
    shoe_model = apps.get_model('main_app', 'Shoe')
    unique_brands_model = apps.get_model('main_app', 'UniqueBrands')

    unique_brand_names = shoe_model.objects.values_list('brand', flat=True).distinct()

    unique_brands_model.objects.bulk_create([unique_brands_model(brand_name=b) for b in unique_brand_names])


def reverse_unique_brands(apps, schema_editor) -> None:
    unique_brands_model = apps.get_model('main_app', 'UniqueBrands')
    unique_brands_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(set_unique_brands, reverse_unique_brands)
    ]
