# Generated by Django 5.0.4 on 2024-06-29 18:59

from django.db import migrations


def set_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    phones = smartphone_model.objects.all()

    for phone in phones:
        phone.price = len(phone.brand) * 120

    smartphone_model.objects.bulk_update(phones, ['price'])


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    phones = smartphone_model.objects.all()

    for phone in phones:
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = 'Cheap'

    smartphone_model.objects.bulk_update(phones, ['category'])


def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reverse_price_and_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    phones = smartphone_model.objects.all()

    for phone in phones:
        phone.category = smartphone_model._meta.get_field('category').default
        phone.price = smartphone_model._meta.get_field('price').default

    smartphone_model.objects.bulk_update(phones, ['category', 'price'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_price_and_category)
    ]
