# Generated by Django 5.0.4 on 2024-07-13 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customer_email_alter_customer_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website_url',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
    ]
