# Generated by Django 5.0.4 on 2024-08-03 11:38

import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_astronaut_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[main_app.validators.validate_digits]),
        ),
    ]
